src/accounts/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path(
        "password-change/", views.PasswordChangeView.as_view(), name="password-change"
    ),
    path("password-reset/", views.PasswordResetView.as_view(), name="password-reset"),
    path(
        "password-reset-done/",
        views.PasswordResetDoneView.as_view(),
        name="password-reset-done",
    ),
    url(
        r"^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.PasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
]

src/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
import accounts.urls
import montedb.urls
from . import views

# Personalized admin site settings like title and header
admin.site.site_title = "Montehelper Site Admin"
admin.site.site_header = "Montehelper Administration"

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("reports/", views.Reports.as_view()),
    path("montedb/", include(montedb.urls)),
    path("grappelli/", include('grappelli.urls')),
    path("admin/", admin.site.urls),
    path("", include(accounts.urls)),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

src/montedb/urls.py
from django.urls import path
from .views import AdultsView, ChildrenView, ParentFeePrintView

app_name = 'montedb'

urlpatterns = [
    path('children/', ChildrenView.as_view(), name='child-list'),
    path('adults/', AdultsView.as_view(), name='adult-list'),
    path('fee/<int:pk>/', ParentFeePrintView.as_view(), name='parental-contribution')
]

src/templates/_brandname.html
Montehelfer

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load i18n %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Oliver Bienert">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap table CSS -->
    <link href="{% static 'bootstrap/css/bootstrap-table.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
        <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>

{% block navbar %}
    <div class="navbar navbar-expand-md navbar-dark sticky-top bg-dark" role="navigation">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'home' %}">
            {% block navbar-brand %}
                <img
                        src="{% static 'site/img/leuchtturm_logo.png' %}"
                        alt="logo"
                        class="d-inline-block align-top border"
                        width="30"
                        height="30"
                >
                {% include "_brandname.html" %}
            {% endblock %}
        </a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                    <li class="nav-item dropdown ">
                        <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button">
                            {{ user.get_full_name|truncatechars:20 }}
                            <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" role="menu">
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">{% trans 'Logout' %}</a>
                            <a class="dropdown-item" href="{% url 'accounts:password-change' %}">{% trans 'Password Change' %}</a>
                        </div>
                    </li>
                {% else %}
                    <a class="btn btn-primary" href="{% url 'accounts:login' %}" role="button">{% trans 'Log in '%}</a>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock navbar %}

{% block splash %}
{% endblock splash %}

{% block container %}
{% endblock container %}


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'jquery/js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'jquery/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap-table.min.js' %}"></script>
<script src="{% static 'bootstrap/extensions/bootstrap-table-mobile.min.js' %}"></script>
<script src="https://kit.fontawesome.com/c94b753db0.js" crossorigin="anonymous"></script>
{% block scripts %}
{% endblock scripts %}
</body>
</html>

src/templates/home.html
{% extends "base.html" %}
{% load i18n %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Nach Hause{% endblock %}

{% block navbar %}
    {{ block.super }}
{% endblock %}

{% block splash %}
    {% if not user.is_authenticated %}
        <div class="jumbotron jumbotron-carousel corporate-jumbo">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-8">
                        <h1>{% include "_brandname.html" %}</h1>
                        <p>{% trans 'Fees, Notifications, Authorities & Co.' %}</p>
                        <p style="font-size: xx-small">{% trans 'Image by' %} <a
                                href="https://pixabay.com/de/users/creativesignature-1460253/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1633406">Chris
                            Stermitz</a> {% trans 'at' %} <a
                                href="https://pixabay.com/de/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1633406">Pixabay</a>
                        </p>
                    </div>
                    <div class="col-md-4 col-sm-4">

                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock splash %}

{% block container %}

    {% if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link {{ home }}" href="{% url 'home' %}">
                                    {% trans 'Dashboard' %}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {{ children }}" href="{% url 'montedb:child-list' %}">
                                    {% trans 'Children' %}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {{ adults }}" href="{% url 'montedb:adult-list' %}">
                                    {% trans 'Adults' %}
                                </a>
                            </li>
                        </ul>

                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                            <span>{% trans 'Saved reports' %}</span>
                            <a class="d-flex align-items-center text-muted" href="#">
                                <span data-feather="plus-circle"></span>
                            </a>
                        </h6>
                        <div class="reports"></div>
                    </div>
                </nav>


                <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
                        {% block main %}
                            <h5>{% trans 'Dashboard' %}</h5>
                            <div class="btn-toolbar mb-2 mb-md-0">
                                <div class="btn-group mr-2">
                                    <button class="btn btn-sm btn-outline-secondary">{% trans 'Share' %}</button>
                                    <button class="btn btn-sm btn-outline-secondary">{% trans 'Export' %}</button>
                                </div>
                                <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                                    <span data-feather="calendar"></span>
                                    {% trans 'This week' %}
                                </button>
                            </div>
                        {% endblock main %}
                    </div>
                </main>

            </div>
        </div>
    {% endif %}
{% endblock container %}

{% block scripts %}
    <script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}

src/templates/reports.html
<div class="list-group">
	{% for report in reports %}
		<a href="{{ report.url }}" class="list-group-item list-group-item-action flex-column align-items-start">
			<div class="d-flex w-100 justify-content-between">
				<h5 class="mb-1">{{ report.type }}</h5>
				<small>{{ report.date }}</small>
			</div>
			<p class="mb-1">{{ report.name }}</p>
		</a>
	{% endfor %}
</div>