src/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
import accounts.urls
import montedb.urls
from . import views

# Personalized admin site settings like title and header
admin.site.site_title = "Montehelper Site Admin"
admin.site.site_header = "Montehelper Administration"

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("reports/", views.Reports.as_view()),
    path("montedb/", include(montedb.urls)),
    path("grappelli/", include('grappelli.urls')),
    path("admin/", admin.site.urls),
    path("", include(accounts.urls)),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

src/montedb/urls.py
from django.urls import path
from .views import AdultsView, ChildrenView, ParentFeePrintView

app_name = 'montedb'

urlpatterns = [
    path('children/', ChildrenView.as_view(), name='child-list'),
    path('adults/', AdultsView.as_view(), name='adult-list'),
    path('fee/<int:pk>/', ParentFeePrintView.as_view(), name='parental-contribution')
]

src/montedb/models.py
import datetime

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from django_jsonfield_backport.models import JSONField


def first_day_of_next_month():
    dt = datetime.date.today()
    return (dt.replace(day=1) + datetime.timedelta(days=32)).replace(day=1)


class Address(models.Model):
    street = models.CharField(_('Street'), max_length=255)
    house_number = models.CharField(_('House number'), max_length=255, blank=True, null=True)
    zip_code = models.CharField(_('ZIP code'), max_length=255)
    city = models.CharField(_('City'), max_length=255)

    class Meta:
        verbose_name = _('Address')
        verbose_name_plural = _('Addresses')

    def __str__(self):
        return '{} {}, {} {}'.format(self.street, self.house_number, self.zip_code, self.city)


class Person(models.Model):
    last_name = models.CharField(_('Last name'), max_length=255)
    first_name = models.CharField(_('First name'), max_length=255)
    birth_date = models.DateField(_('Birth date'), null=True, blank=True)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class Child(Person):
    birth_place = models.CharField(_('Birth place'), max_length=255)
    care_time = models.IntegerField(_('Care time'), null=False, default=4)
    kita = models.BooleanField(_('Day-care centre'))

    class Meta:
        verbose_name = _('Child')
        verbose_name_plural = _('Children')

    def get_absolute_url(self):
        return reverse('montedb:child-update', kwargs={'pk': self.pk})

    def age(self):
        today = datetime.date.today()
        born = self.birth_date
        return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

    age.short_description = _('Age')

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class Adult(Person):
    iban = models.CharField('IBAN', max_length=32, blank=True)
    partner = models.OneToOneField('self', verbose_name=_('Partner'), on_delete=models.SET_NULL, blank=True, null=True)
    address = models.ForeignKey(Address, verbose_name=_('Address'), related_name='adults', on_delete=models.SET_NULL,
                                blank=True, null=True)
    children = models.ManyToManyField(Child, through='AdultChild', verbose_name=_('Children'), related_name='adults')
    club_member = models.BooleanField(_('Club member'), default=False)
    staff = models.BooleanField(_('Staff'), default=False)
    household_size = models.IntegerField(_('Children with child allowance'), null=True, blank=True,
                                         validators=[MaxValueValidator(10), MinValueValidator(1)])
    no_kiga_fee = models.BooleanField(_('No Kindergarten fee'), default=False)

    class Meta:
        verbose_name = _('Adult')
        verbose_name_plural = _('Adults')

    def save(self, recursive=True, *args, **kwargs):
        super(Person, self).save()
        if self.partner is None:
            Adult.objects.all().filter(partner=self).update(partner=None)
        else:
            self.partner.partner = self
            if recursive:
                self.partner.save(recursive=False)

    def get_absolute_url(self):
        return reverse('montedb:adult-update', kwargs={'pk': self.pk})

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class AdultChild(models.Model):
    MOTHER = 'mother'
    FATHER = 'father'
    GRANDMOTHER = 'grandmother'
    GRANDFATHER = 'grandfather'
    OTHER = 'other'
    KINSHIP_TYPE = [
        (MOTHER, _('Mother')),
        (FATHER, _('Father')),
        (GRANDMOTHER, _('Grandmother')),
        (GRANDMOTHER, _('Grandfather')),
        (OTHER, _('Other'))
    ]
    adult = models.ForeignKey(Adult, on_delete=models.CASCADE, verbose_name=_('Adult'))
    child = models.ForeignKey(Child, on_delete=models.CASCADE, verbose_name=_('Child'))
    kinship = models.CharField(_('Degree of kinship'), max_length=20, choices=KINSHIP_TYPE, default=MOTHER)
    liable = models.BooleanField(_('Liable to contribution'), default=False)
    max_contribution = models.BooleanField(_('Max contribution'), default=False)
    payer = models.BooleanField(_('Payer'), default=False)

    class Meta:
        verbose_name = _('Degree of kinship')
        verbose_name_plural = _('Degrees of kinship')
        unique_together = (('adult', 'child',), ('child', 'kinship',),)


class Income(models.Model):
    SALARY = 'salary'
    INCOME = 'income'
    UNEMPLOYMENT = 'unemployment'
    OTHER_PAYMENTS = 'other_payments'
    DEDUCTION = 'deduction'
    INCOME_TYPE = [
        (SALARY, _('Salary')),
        (INCOME, _('Income')),
        (UNEMPLOYMENT, _('Unemployment')),
        (OTHER_PAYMENTS, _('Other payments')),
        (DEDUCTION, _('Deduction'))
    ]
    amount = models.IntegerField(_('Amount'))
    type = models.CharField(
        _('Type'),
        max_length=20,
        choices=INCOME_TYPE,
        default=SALARY
    )
    adult = models.ForeignKey(Adult, models.CASCADE, verbose_name=_('Adult'), related_name='income')

    class Meta:
        verbose_name = _('Income')
        verbose_name_plural = _('Incomes')

    def __str__(self):
        return "{}: {}".format(self.type, self.amount)


class PhoneNumber(models.Model):
    PRIVATE = 'private'
    WORK = 'work'
    MOBILE = 'mobile'
    FAX = 'fax'
    FON_NUMBER_TYPE = [
        (PRIVATE, _('Private')),
        (WORK, _('Work')),
        (MOBILE, _('Mobile')),
        (FAX, _('Fax'))
    ]
    phone_number = PhoneNumberField(_('Phone number'))
    type = models.CharField(
        _('Type'),
        max_length=10,
        choices=FON_NUMBER_TYPE,
        default=PRIVATE
    )
    adult = models.ForeignKey(Adult, models.CASCADE, verbose_name=_('Adult'))

    class Meta:
        verbose_name = _('Phone number')
        verbose_name_plural = _('Phone numbers')
        unique_together = (('adult', 'phone_number'),)


class EmailAddress(models.Model):
    PRIVATE = 'private'
    WORK = 'work'
    EMAIL_ADDRESS_TYPE = [
        (PRIVATE, _('Private')),
        (WORK, _('Work')),
    ]
    email_address = models.EmailField(_('E-Mail address'))
    type = models.CharField(
        _('Type'),
        max_length=10,
        choices=EMAIL_ADDRESS_TYPE,
        default=PRIVATE
    )
    adult = models.ForeignKey(Adult, models.CASCADE, verbose_name=_('Adult'))

    class Meta:
        verbose_name = _('E-Mail address')
        verbose_name_plural = _('E-Mail addresses')
        unique_together = (('adult', 'email_address'),)


class Ruling(models.Model):
    EXTENDED_DAY_TIME = 'ext_day_time'
    EXTENDED_CARE_TIME = 'ext_care_time'
    RIGHT_TO_REQUEST = 'right_to_request'
    FEE_PAYMENT_BY_COUNTY = 'fee_by_county'
    LUNCH_PAYMENT_BY_COUNTY = 'lunch_by_county'
    RULING_TYPE = [
        (EXTENDED_DAY_TIME, _('Extended day time')),
        (EXTENDED_CARE_TIME, _('Extended care time')),
        (RIGHT_TO_REQUEST, _('Right to request and vote (available care service)')),
        (FEE_PAYMENT_BY_COUNTY, _('Fee payment by county')),
        (LUNCH_PAYMENT_BY_COUNTY, _('Lunch payment by county'))

    ]
    type = models.CharField(
        _('Ruling type'),
        max_length=10,
        choices=RULING_TYPE,
    )
    valid_from = models.DateField(_('Valid from'), default=datetime.date.today)
    valid_to = models.DateField(_('Valid to'), default=datetime.date.today)
    # document = models.FileField(_('Document'), upload_to="documents/")
    child = models.ForeignKey(Child, models.CASCADE, verbose_name=_('Child'))

    class Meta:
        verbose_name = _('Ruling')
        verbose_name_plural = _('Rulings')


class Report(models.Model):

    PARENTAL_CONTRIBUTION = 'parental_contribution'
    REPORT_TYPE = [
        (PARENTAL_CONTRIBUTION, _('Parental contribution'))
    ]
    person = models.ForeignKey(Person, models.CASCADE, verbose_name=_('Person'))
    date = models.DateField(_('Created'), default=datetime.date.today)
    valid_from = models.DateField(_('Valid from'), default=first_day_of_next_month)
    type = models.CharField(
        _('Report type'),
        max_length=30,
        choices=REPORT_TYPE,
    )
    data = JSONField()

    class Meta:
        verbose_name = _('Report')
        verbose_name_plural = _('Reports')

src/montedb/views.py
import functools
import ssl
from os.path import join

from django.conf import settings
from django.templatetags.static import static
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django_tables2 import SingleTableView
from django_weasyprint import WeasyTemplateResponse, WeasyTemplateResponseMixin
from django_weasyprint.utils import django_url_fetcher

from config.utils import get_reports
from .decorators import process_report_response
from .fees import Fee
from .models import Adult, Child
from .tables import AdultTable, ChildTable


class ChildrenView(SingleTableView):
    template_name = "montedb/child_list.html"
    table_class = ChildTable
    model = Child

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ChildrenView, self).get_context_data(**kwargs)
        context['children'] = 'active'
        context['reports'] = get_reports()
        return context


class AdultsView(SingleTableView):
    template_name = "montedb/adult_list.html"
    table_class = AdultTable
    model = Adult

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(AdultsView, self).get_context_data(**kwargs)
        context['adults'] = 'active'
        context['reports'] = get_reports()
        return context


@method_decorator(process_report_response, name='dispatch')
class ParentFeeView(TemplateView):
    template_name = "montedb/parent_fee.html"

    def get_context_data(self, **kwargs):
        adult = Adult.objects.get(pk=kwargs['pk'])
        context = super(ParentFeeView, self).get_context_data(**kwargs)

        fee = Fee(adult)
        data = {
            'payer': fee.payer,
            'adults': fee.adult_calculations,
            'children': fee.children_calculations
        }
        meta = {
            'person': fee.person,
            'type': 'parental_contribution'
        }
        context['data'] = data
        context['meta'] = meta
        return context


class CustomWeasyTemplateResponse(WeasyTemplateResponse):
    # customized response class to change the default URL fetcher
    def get_url_fetcher(self):
        # disable host and certificate check
        context = ssl.create_default_context()
        context.check_hostname = False
        context.verify_mode = ssl.CERT_NONE
        return functools.partial(django_url_fetcher, ssl_context=context)


class ParentFeePrintView(WeasyTemplateResponseMixin, ParentFeeView):
    # output of MyModelView rendered as PDF with hardcoded CSS
    pdf_stylesheets = [
        join(settings.BASE_DIR, static('site/css/fee.css').lstrip('/')),
    ]
    #
    # show pdf in-line (default: True, show download dialog)
    pdf_attachment = False
    # custom response class to configure url-fetcher
    response_class = CustomWeasyTemplateResponse

src/montedb/templates/montedb/adult_list.html
{% extends "montedb/table_base.html" %}
{% load i18n %}

{% load staticfiles %}

{% load render_table from django_tables2 %}

{% block title %}{{ block.super }}{% trans 'Adults' %}{% endblock %}

{% block editing %}
    <h5>{% block table_heading %}{% trans 'Adults' %}{% endblock %}</h5>
{% endblock %}

{% block table %}
    {% render_table table %}
{% endblock table %}

src/montedb/templates/montedb/child_list.html
{% extends "montedb/table_base.html" %}
{% load i18n %}
{% load staticfiles %}

{% load render_table from django_tables2 %}

{% block title %}{{ block.super }}{% trans 'Children' %}{% endblock %}

{% block editing %}
    <h5>{% block table_heading %}{% trans 'Children' %}{% endblock %}</h5>
{% endblock %}

{% block table %}
    {% render_table table %}
{% endblock table %}

src/montedb/templates/montedb/parent_contribution_button.html
{% load i18n %}

<a class="feebutton" href="{% url 'montedb:parental-contribution' record.id %}" title="{% trans 'Fee' %}">
    <i class="fas fa-file-invoice"></i>
</a>

src/montedb/templates/montedb/parent_fee.html
{% load custom_tags l10n %}

<div>
    <h1>Elternbeitragsrechnung</h1>
    <p>
        {{ config.REPORT_HEADER | linebreaks}}
    </p>
    <p>Beitragsbescheid, gültig ab: {{ valid_from }}</p>
    <h2>Empfänger</h2>
    <p>
        {{ data.payer.last_name }}, {{ data.payer.first_name }}<br>
        {{ data.payer.street }} {{ data.payer.house_number }}<br>
        {{ data.payer.zip_code}} {{ data.payer.city }}
    </p>
    <h2>Beiträge</h2>
    <p>Gemäß § 17 des Kindertagesstättengesetzes (KitaG Land Brandenburg) vom 27.06.2004  und der von der Mitgliederversammlung zuletzt beschlossenen Beitragsordnung wird Ihr monatlicher Beitrag für die Nutzung der Einrichtungen des Freie Montessorischule Barnim e.V. wie folgt festgesetzt:</p>
    <table style="border-width:0;">
        <tbody>
        {% for child, childCalculation in data.children.items %}
            <tr style="font-weight: bold">
                <td>{{ child }}</td>
                <td>{{ childCalculation.fee|euro }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <h2>Berechnung</h2>
    <table class="report">
        <tr>
            <th>Name</th>
            <th>Eink.</th>
            <th>Kinderg.</th>
            <th>Erw. Betr.</th>
            <th>Berücks. Eink.</th>
            <th>Betrag</th>
        </tr>
        {% for child, childCalculation in data.children.items %}
        <tr>
            <td>{{ child }}</td>
            <td>{{ childCalculation.income|euro }}</td>
            <td></td>
            <td></td>
            <td>{{ childCalculation.incomeApplied|euro }}</td>
            <td>{{ childCalculation.fee|euro }}</td>
        </tr>
        {% endfor %}
    </table>
    <h2 id="page-break">Einkommen</h2>
    <table class="report">
        <tr>
            <th>Name</th>
            <th>Abhäng.</th>
            <th>Selbst.</th>
            <th>AA</th>
            <th>Unterh.</th>
            <th>Sonst.</th>
            <th>Abzügl.</th>
            <th>Gesamt</th>
        </tr>
        {% for adult, adultCalculation in data.adults.items %}
        <tr>
            <td>{{ adult }}</td>
            <td>{{ adultCalculation.salary|euro }}</td>
            <td>{{ adultCalculation.income|euro }}</td>
            <td>{{ adultCalculation.unemployment|euro }}</td>
            <td></td>
            <td>{{ adultCalculation.other_payments|euro }}</td>
            <td>{{ adultCalculation.deduction|euro }}</td>
            <td>{{ adultCalculation.total_income|euro }}</td>
        </tr>
        {% endfor %}
    </table>
    <h3>Bemerkungen</h3>
    <p>{{ message }}</p>
    <p>Die Elternbeiträge werden zum 15. des Monats eingezogen.</p>
    <p>Für eventuell erforderlich werdende Mahnungen werden jeweils 5,- € Gebühren erhoben.<br>Veränderungen des Gesamteinkommens von mehr als 5 % müssen dem Vorstand unter Vorlage entsprechender Bescheide zur Kenntnis gegeben werden.</p>
    <p>Dieser Beitragsbescheid ersetzt alle früheren Bescheide.</p>
    <p>Eberswalde, den {{ created }}</p>
</div>

src/montedb/templates/montedb/table_base.html
{% extends "home.html" %}

{% block navbar %}
    {{ block.super }}
{% endblock %}

{% block main %}

    <div class="text-left">
          {% block editing %}
          {% endblock %}
          {% block table %}
          {% endblock %}
    </div>

{% endblock main %}